CREATE USER swim;

CREATE DATABASE testing WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

CREATE DATABASE smdb WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'en_US.utf8' LC_CTYPE = 'en_US.utf8';

GRANT ALL PRIVILEGES ON DATABASE smdb TO swim;
